In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-11-02 12:50:35.620386: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2154, 9024, 7060, 5593],
 [2154, 9024, 7060, 7013],
 [2154, 3221, 7060, 422],
 [3787, 2928, 6276, 8229, 9572],
 [3787, 2928, 6276, 8229, 1029],
 [5623, 2154, 3164, 7060, 4469],
 [1175, 7125, 2380, 8229]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2154 9024 7060 5593]
 [   0    0    0    0 2154 9024 7060 7013]
 [   0    0    0    0 2154 3221 7060  422]
 [   0    0    0 3787 2928 6276 8229 9572]
 [   0    0    0 3787 2928 6276 8229 1029]
 [   0    0    0 5623 2154 3164 7060 4469]
 [   0    0    0    0 1175 7125 2380 8229]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 153ms/step


array([[[ 0.03836279,  0.02309033,  0.01252362,  0.01824853,
          0.01616401,  0.0203176 ,  0.04278747,  0.01178235,
         -0.00076721, -0.04119917],
        [ 0.03836279,  0.02309033,  0.01252362,  0.01824853,
          0.01616401,  0.0203176 ,  0.04278747,  0.01178235,
         -0.00076721, -0.04119917],
        [ 0.03836279,  0.02309033,  0.01252362,  0.01824853,
          0.01616401,  0.0203176 ,  0.04278747,  0.01178235,
         -0.00076721, -0.04119917],
        [ 0.03836279,  0.02309033,  0.01252362,  0.01824853,
          0.01616401,  0.0203176 ,  0.04278747,  0.01178235,
         -0.00076721, -0.04119917],
        [-0.04766761, -0.03407931,  0.00514404, -0.04735441,
         -0.026925  ,  0.03355617,  0.01511921,  0.01780048,
         -0.04501694,  0.04220215],
        [-0.03443753, -0.04000134, -0.03130956, -0.00788601,
         -0.03311179,  0.02362862,  0.00884682,  0.03522496,
         -0.04715119, -0.01494821],
        [ 0.01238162, -0.04162692,  0.04637711, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2154, 9024, 7060, 5593], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 38ms/step


array([[ 0.03836279,  0.02309033,  0.01252362,  0.01824853,  0.01616401,
         0.0203176 ,  0.04278747,  0.01178235, -0.00076721, -0.04119917],
       [ 0.03836279,  0.02309033,  0.01252362,  0.01824853,  0.01616401,
         0.0203176 ,  0.04278747,  0.01178235, -0.00076721, -0.04119917],
       [ 0.03836279,  0.02309033,  0.01252362,  0.01824853,  0.01616401,
         0.0203176 ,  0.04278747,  0.01178235, -0.00076721, -0.04119917],
       [ 0.03836279,  0.02309033,  0.01252362,  0.01824853,  0.01616401,
         0.0203176 ,  0.04278747,  0.01178235, -0.00076721, -0.04119917],
       [-0.04766761, -0.03407931,  0.00514404, -0.04735441, -0.026925  ,
         0.03355617,  0.01511921,  0.01780048, -0.04501694,  0.04220215],
       [-0.03443753, -0.04000134, -0.03130956, -0.00788601, -0.03311179,
         0.02362862,  0.00884682,  0.03522496, -0.04715119, -0.01494821],
       [ 0.01238162, -0.04162692,  0.04637711, -0.03263185, -0.00659026,
        -0.03744755, -0.00176876,  0.03245351